#!/usr/bin/env python3
"""Generate the authorization Flyway seed migration from the supplied EBCDIC IMS image.

`jcl/LOADPADB.JCL` runs `PAUDBLOD`, which reads a GSAM input file and inserts `PAUTSUM0` roots and
`PAUTDTL1` children into DBPAUTP0. The target equivalent is a Flyway migration that inserts the
same rows into `pending_auth_summary` and `pending_auth_detail`, generated straight from the
supplied unload image so every seeded value is traceable to source data rather than hand written.

Usage: python3 modernization/tools/generate_authorization_seed_sql.py
"""
from __future__ import annotations

import pathlib
from decimal import Decimal

from ims_authorization_unload import Detail, Summary, decode_unload, default_unload_path

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
TARGET = (REPO_ROOT / "modernization" / "authorization-service" / "src" / "main" / "resources"
          / "db" / "migration" / "V2__load_authorization_sample_data.sql")

HEADER = """-- Authorization sample data, the target equivalent of jcl/LOADPADB.JCL running PAUDBLOD.
--
-- Generated by modernization/tools/generate_authorization_seed_sql.py from
-- app/app-authorization-ims-db2-mq/data/EBCDIC/AWS.M2.CARDDEMO.IMSDATA.DBPAUTP0.dat, the supplied
-- EBCDIC unload of HIDAM database DBPAUTP0. The generator applies the copybook layouts
-- (CIPAUSMY, CIPAUDTY): packed decimal money and key fields, binary counters, zoned decimal
-- customer ids and fixed-width EBCDIC text converted to UTF-8. Do not edit by hand; re-run the
-- generator. modernization/tools/reconcile_authorization_data.py reconciles the loaded rows back
-- to the same image.
--
-- {summaries} PAUTSUM0 roots, {details} PAUTDTL1 children.
"""


def quote(value: str) -> str:
    """Return a SQL string literal, preserving the fixed-width trailing blanks of the layout."""
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def money(value: Decimal) -> str:
    """Return a money literal with the two implied decimals of the packed source field."""
    return f"{value:.2f}"


def summary_values(summary: Summary) -> str:
    """Render one `pending_auth_summary` row."""
    return (f"({summary.acct_id}, {summary.cust_id}, {quote(summary.auth_status)}, "
            f"{quote(summary.account_status)}, {money(summary.credit_limit)}, "
            f"{money(summary.cash_limit)}, {money(summary.credit_balance)}, "
            f"{money(summary.cash_balance)}, {summary.approved_auth_cnt}, "
            f"{summary.declined_auth_cnt}, {money(summary.approved_auth_amt)}, "
            f"{money(summary.declined_auth_amt)})")


def detail_values(detail: Detail) -> str:
    """Render one `pending_auth_detail` row."""
    return (f"({detail.acct_id}, {quote(detail.auth_key)}, {detail.auth_date_9c}, "
            f"{detail.auth_time_9c}, {quote(detail.auth_orig_date)}, "
            f"{quote(detail.auth_orig_time)}, {quote(detail.card_num)}, "
            f"{quote(detail.auth_type)}, {quote(detail.card_expiry_date)}, "
            f"{quote(detail.message_type)}, {quote(detail.message_source)}, "
            f"{quote(detail.auth_id_code)}, {quote(detail.auth_resp_code)}, "
            f"{quote(detail.auth_resp_reason)}, {quote(f'{detail.processing_code:06d}')}, "
            f"{money(detail.transaction_amt)}, {money(detail.approved_amt)}, "
            f"{quote(detail.merchant_category_code)}, {quote(detail.acqr_country_code)}, "
            f"{quote(detail.pos_entry_mode)}, {quote(detail.merchant_id)}, "
            f"{quote(detail.merchant_name)}, {quote(detail.merchant_city)}, "
            f"{quote(detail.merchant_state)}, {quote(detail.merchant_zip)}, "
            f"{quote(detail.transaction_id)}, {quote(detail.match_status)}, "
            f"{quote(detail.auth_fraud)}, {quote(detail.fraud_rpt_date)})")


def build_sql(summaries: list[Summary], details: list[Detail], anomalies: list[str]) -> str:
    """Build the whole migration text for the decoded segments."""
    lines = [HEADER.format(summaries=len(summaries), details=len(details))]
    for anomaly in anomalies:
        lines.append(f"-- Not seeded, reported as supplied-data defect UCR-30: {anomaly}\n")
    lines.append("\nINSERT INTO pending_auth_summary (acct_id, cust_id, auth_status, "
                 "account_status, credit_limit, cash_limit,\n"
                 "                                  credit_balance, cash_balance, "
                 "approved_auth_cnt, declined_auth_cnt,\n"
                 "                                  approved_auth_amt, declined_auth_amt)\nVALUES\n")
    lines.append(",\n".join(f"    {summary_values(summary)}" for summary in summaries))
    lines.append(";\n")
    lines.append("\nINSERT INTO pending_auth_detail (acct_id, auth_key, auth_date_9c, "
                 "auth_time_9c, auth_orig_date,\n"
                 "                                 auth_orig_time, card_num, auth_type, "
                 "card_expiry_date, message_type,\n"
                 "                                 message_source, auth_id_code, auth_resp_code, "
                 "auth_resp_reason,\n"
                 "                                 processing_code, transaction_amt, "
                 "approved_amt, merchant_category_code,\n"
                 "                                 acqr_country_code, pos_entry_mode, "
                 "merchant_id, merchant_name,\n"
                 "                                 merchant_city, merchant_state, merchant_zip, "
                 "transaction_id,\n"
                 "                                 match_status, auth_fraud, fraud_rpt_date)\n"
                 "VALUES\n")
    lines.append(",\n".join(f"    {detail_values(detail)}" for detail in details))
    lines.append(";\n")
    return "".join(lines)


def main() -> int:
    """Decode the supplied unload image and write the seed migration."""
    summaries, details, anomalies = decode_unload(default_unload_path(REPO_ROOT))
    TARGET.write_text(build_sql(summaries, details, anomalies), encoding="utf-8")
    print(f"wrote {TARGET} ({len(summaries)} summaries, {len(details)} details, "
          f"{len(anomalies)} anomalies)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
